# Generated by Django 6.0.2 on 2026-02-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Profile_Pic',
        ),
    ]
